### PR TITLE
Remove data science challenge

### PR DESCRIPTION
**Pull request by dhaigh**
It's really annoying when people submit solutions to this. We can't use it for devs or designers or BAs or QAs. What is it for?

### CODE REVIEW

**Comment by adamlyons2** [comment]
I can't remember why exactly we added this back in the day... I feel like we were trying to hire someone into a data sciencey type role - definitely something you could ask of a BA though.  
Oh we were going to fully overhaul the settings page, did some analysis on defaults being changed etc.  

It should be the same level of complexity for someone with a data science background as the pings challenge would be for a back end developer.  You read in the spreadsheet, ask some questions about it that you couldn't answer by hand/just looking at it.  Passing marks for me were
- if you could read, manipulate and perform some basic analysis on a csv file in anything but excel
- could demonstrate a logical train of thought well as part of this.  

I'm not attached to it, only ever had a couple of submissions.  If you have developers submitting it though I think that's a different problem...

**Comment by dhaigh** [comment]
I've had at least two or three submissions because i've just said to people "go do something in the work samples repo", but i now realise i can't do that for that reason. if you think i should be more specific about what challenges i ask people to do then fair enough, but when in the near future are we going to hire for a data scientist role? i don't think we've ever sent this to a BA before?

**Comment by adamlyons2** [comment]
So yeah would recommend being more specific/getting them to pick a relevant challenge - on the same note you're not going to get a designer to do the pings challenge?

And nah we hardly ever use this - I'm not going to miss it and can get people to submit other shit if we do hire for a data scientist

**Comment by jling90** [comment]
yeah pretty keen to scrap this for now. josh has used it for hiring in the past - we got one data science intern in manila but it didn't work out well for a number of reasons. it could be a helpful filter for hiring into growth at some stage, but like adam pointed out we don't have a clear understanding of what the role would entail right now. i'm keen to chat about some potential refinements to the challenge further down the track

**Comment by dhaigh** [comment]
dave had the idea of moving into a separate directory? like "/old challenges/data science" or something like that? with a readme saying like "we dont use these any more" or something like that?

**Pull request merged**
