### PR TITLE
Ping's README was using single quotes (invalid JSON)

### PR DESCRIPTION
**Pull request by lewisjb**
If this was intentional, then ignore me

### CODE REVIEW

**Comment by deecewan** [comment]
not necessarily JSON.  the code block specifies javascript, and that is valid javascript.

I believe it says it wants a hash.  That's a JS Object, or a ruby hash, and I think the specified code is valid for both

**Comment by lewisjb** [comment]
Yeah, fair enough; just thought that since the tests use `JSON.parse` (meaning a server that uses single quotes will fail the test), having examples use valid syntax for the tests would be clearer.

**Comment by daveallie** [comment]
@lewisjb you're right, the code is supposed to represent potential output from the app.

While you're there could you please change all the appropriate code block tags from `javascript` to `json`, if I'd done that from the start the syntax highlighter would have picked it up.

**Comment by ghiculescu** [comment]
thanks @lewisjb 💯 !

**Pull request merged**
